### ISSUE TITLE
Order of installed apps

### ISSUE THREAD

**Issue by allcaps** [fourdigits/wagtail_textract#10]
In the readme it says:

`Add to your Django INSTALLED_APPS, after wagtail.documents.` 

Why after? From de [Django Docs](https://docs.djangoproject.com/en/2.0/ref/settings/#std:setting-INSTALLED_APPS):

> When several applications provide different versions of the same resource (template, static file, management command, translation), the application listed first in INSTALLED_APPS has precedence.

Or is this order not relevant for Python code?

**Comment by khink** [comment]
Using WAGTAILDOCS_DOCUMENT_MODEL made that statement obsolete and it likely was incorrect anyway as you have pointed out. Feel free to remove it (we're accepting PR's) ;)

**Comment by khink** [comment]
Thanks!
